### ISSUE TITLE
Unable to compile on win32

### ISSUE THREAD

**Issue by snunez1** [hyotang666/prompt-for#2]
; Fetching #<URL "http://beta.quicklisp.org/archive/prompt-for/2021-10-20/prompt-for-20211020-git.tgz">
; 4.26KB
==================================================
4,365 bytes in 0.01 seconds (302.21KB/sec)
; Loading "prompt-for"
[package prompt-for]..
; 
; caught ERROR:
;   READ error during COMPILE-FILE: Symbol "TCGETATTR" not found in the SB-POSIX package. Line: 106, Column: 39, File-Position: 3643 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file S:\\quicklisp\\dists\\quicklisp\\software\\prompt-for-20211020-git\\prompt-for.lisp" {100A6F19B3}>

**Comment by snunez1** [comment]
Is it possible to conditionalise so that it can be used without secrets on non-UNIX operating systems?

**Comment by hyotang666** [comment]
Thank you to report it.
It seems caused by incorrect read time conditional branching because sb-posix is for a unix-like system, not for windows.

> Is it possible to conditionalise so that it can be used without secrets on non-UNIX operating systems?

The commit above will do it.
With not being supported environment, in reading time, a warning about not being supported is signaled and in the time :SECRET method is called an error is signaled.
If you do not call :SECRET method, you can use `prompt-for` in any supported implementation.

In fact, I do not have a windows lisp dev environment, so the commit above is not tested.
Please feel free to re-open the issue if the commit does not fix it.
